kind: ZosConnect
apiVersion: zosconnect.zcon.ibm.com/v1
metadata:
  name: zc
spec:
  deployment:
    containerPort: 9443
    image: 'icr.io/zpot/zc-pot-api:pot99'
    pullPolicy: IfNotPresent
    replicas: 1
  license:
    accept: true
  service:
    port: 9443
    targetPort: 9443
    type: ClusterIP
  expose: true
  route:
    termination: passthrough
  version: v1.0.6
